In [2]:
# 배열을 이용하여 리스트 처럼 자료를 처리함
# numpy에서는 ndarray를 사용한다
# n-dimension array n차원 배열
# python의 list와 대동소이, 대신 ndarray는 같은데이터타입만 사용 가능함
# ndarray가 list보다 훨씬 메모리도 적게 사용하고 속도도 빠르다.
import numpy as np

In [17]:
a = [1, 2, 3, 4] # python의 list
print("{0}, {1}".format(a, type(a)))
print("{0}, {1}".format(a[0], type(a[0])))

arr = np.array(a) # 리스트로 배열을 만듬 
print("{0}, {1}, {2}".format(arr, type(arr), arr.dtype)) # 배열이기 때문에 콤마가 없음 [1 2 3 4], <class 'numpy.ndarray'>, int32

a = np.array([100, "hello", 3.14]) # 데이터타입 스트링으로 변환
a

[1, 2, 3, 4], <class 'list'>
1, <class 'int'>
[1 2 3 4], <class 'numpy.ndarray'>, int32


array(['100', 'hello', '3.14'], dtype='<U11')

In [34]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
list1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr = np.array(list)
arr1 = np.array(list1)
arr2 = np.array([[[1, 2, 3, 4],[5, 6, 7, 8]]])
print("{0}차원의 array".format(arr.ndim)) # 몇차원이냐?
print("차원의 개수와 원소의 개수 : {0}".format(arr.shape)) # 차원과 원소개수
print("차원의 개수와 원소의 개수 : {0}".format(arr1.shape)) # 차원과 원소개수
print("차원의 개수와 원소의 개수 : {0}".format(arr2.shape)) # 차원과 원소개수
arr.shape = 2, 2, 3
arr


1차원의 array
차원의 개수와 원소의 개수 : (12,)
차원의 개수와 원소의 개수 : (2, 4)
차원의 개수와 원소의 개수 : (1, 2, 4)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
for i in range(len(arr)):
    for j in range(len(arr[i])):
        print("arr[{0}][{1}] = ".format(i, j), arr[i][j], end=" ") # end =" " 한줄띄지말고 이거 붙여
    print("\n")
    

for i in range(arr.shape[0]):
    print("\n")
    for j in range(arr.shape[1]):
        print("arr[{0}][{1}] = {2}".format(i, j, arr[i][j]), end=" ")
    
    
arr.shape[0]

arr[0][0] =  1 arr[0][1] =  2 arr[0][2] =  3 

arr[1][0] =  4 arr[1][1] =  5 arr[1][2] =  6 

arr[2][0] =  7 arr[2][1] =  8 arr[2][2] =  9 

arr[3][0] =  10 arr[3][1] =  11 arr[3][2] =  12 



arr[0][0] = 1 arr[0][1] = 2 arr[0][2] = 3 

arr[1][0] = 4 arr[1][1] = 5 arr[1][2] = 6 

arr[2][0] = 7 arr[2][1] = 8 arr[2][2] = 9 

arr[3][0] = 10 arr[3][1] = 11 arr[3][2] = 12 

4

In [92]:
# numpy array의 데이터 타입 지정
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 3.5])
arr.dtype

# numpy array를 생성할 때 data type을 지정할 수 있어요!!
arr = np.array([1, 2.6, 3.6, 4.9, 5.1], dtype=np.float64)
arr
# 이미 만들어진 numpy array의 데이터 타입을 변경할 수 있다!
arr = arr.astype(np.int32) # 소수점 이하를 다잘라버림
arr

array([1, 2, 3, 4, 5])

In [109]:
# numpy array의 다양한 생성함수
arr = np.array([1, 2, 3, 4, 5]) # basic
arr = np.zeros((3, 4)) # 3행 4열을 만드는데 0을 다 채워서 만들고 기본 데이터 타입은 float64
arr = np.ones((4, 4)) # 4행 4열을 만드는데 1을 다 채워서 만들어라
arr = np.empty((3, 3), dtype=np.int32) # 3행 3열의 공간을 확보하라 값은 보장못함
arr

array([[  18760776,        727,          0],
       [         0,   19728904,        727],
       [         0,          0, 2145845248]])

In [116]:
# ndarray의 자주 사용되는 생성함수
# np.arrange(시작, 끝, 간격) 시작 : inclusive, 끝 : exclusive
import numpy as np
arr = np.arange(0, 10, 1)
arr
arr = np.arange(10)

In [122]:
# ndarray의 생성함수 중 하나
# np.linspace(시작, 끝, 샘플 개수)
# 주어진 범위를 지정한 샘플의 개수로 나누어 정해지는
# 간격으로 연속적인 배열 생성
# 간격 : (끝-시작) / (샘플개수 - 1)
arr = np.linspace(0, 10, 51)
arr

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [141]:
# numpyarray의 shape 조절
arr = np.arange(12)
arr
arr.shape = 2, 6 # shape 을 조절할 수 있지만 이렇게 사용하는 경우는 그닥 없다.
arr

arr = np.arange(12)
arr1 = arr.reshape(4, 3) # reshape는 리턴값이 있다. 뷰 로서 원본과 연계됨
arr1
arr[0] = 100
arr1

if arr1.base is arr: # 이식의 데이터는 어디있는거야?
    print("데이터가 같아요!")
    
arr = np.arange(12)
arr1 = arr.reshape(4, 3).copy() # view를 생성하지 않고 새로운 배열을 생성

if arr1.base is arr: # 이식의 데이터는 어디있는거야?
    print("데이터가 같아요!")
else:
    print("다르다")

데이터가 같아요!
다르다


In [156]:
# 기타 shape 조절 방법
arr = np.arange(0, 12, 1) # numpy array 생성
arr1 = arr.reshape(-1, 2) # 확장된 차원 크기를 기준으로 남은 차원의 크기를  추론하여 배열을 생성한다
arr1

arr = np.arange(0, 100, 1).reshape(5, -1).copy()
arr1 = arr.ravel()
arr1

arr.resize(2, 50) # 원본의  shape이 변경
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [166]:
import numpy as np
arr1 = np.array([[1, 2 ,3], [4, 5, 6]])
arr2 = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
print(arr1)
print(arr2)

# 열의 개수가 맞으면 붙일 수 있다.
arr3 = np.vstack((arr1, arr2))
arr3
arr4 = np.array([[11, 22, 33, 44, 55], [66, 77, 88, 99, 100]])
arr5 = np.hstack((arr1, arr4)) #  행이 같아도 붙일 수 있다.
arr5

[[1 2 3]
 [4 5 6]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


array([[  1,   2,   3,  11,  22,  33,  44,  55],
       [  4,   5,   6,  66,  77,  88,  99, 100]])

In [193]:
# numpy의 indexing
import numpy as np
arr = np.arange(10, 20, 1)
for idx, data in enumerate(arr):
    print ("index : {0}, data : {1}".format(idx, data))

arr = np.arange(0, 5, 1)
arr1 = arr[0:2]
arr[-1:]
arr[1:-1]


arr = np.arange(0, 5, 1)
arr1 = arr[0:2] # 넘파이의 슬라이싱은 뷰다
arr[0] = 1000  # 넘파이의 슬라이싱은 뷰다
arr
arr1

index : 0, data : 10
index : 1, data : 11
index : 2, data : 12
index : 3, data : 13
index : 4, data : 14
index : 5, data : 15
index : 6, data : 16
index : 7, data : 17
index : 8, data : 18
index : 9, data : 19


array([1000,    1])

In [198]:
# numpy array의 연산
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8]) # 넘파이는 계산의 목적의 연산
arr1 * arr2

array([ 5, 12, 21, 32])

In [210]:
# Movielens Dataset
# Group lens 라는 미네소타 대학의 컴퓨터학과 연구실에서 수집한 영화 데이터
# 특정 영화에 대한 선호를 1~5사이의 실수로 표시, 높은점수일수록 선호도가 높다

import numpy as np
data = np.loadtxt("data/movie/ratings.csv", delimiter=",", dtype=np.float64)

data.shape
data[:5,:]
# userid, movieid, rating, timestamp

array([[1.00000000e+00, 1.00000000e+00, 4.00000000e+00, 9.64982703e+08],
       [1.00000000e+00, 3.00000000e+00, 4.00000000e+00, 9.64981247e+08],
       [1.00000000e+00, 6.00000000e+00, 4.00000000e+00, 9.64982224e+08],
       [1.00000000e+00, 4.70000000e+01, 5.00000000e+00, 9.64983815e+08],
       [1.00000000e+00, 5.00000000e+01, 5.00000000e+00, 9.64982931e+08]])

In [244]:
# 모든 영화의 전체 평균 평점
data[:, 2].mean() # 평균구하기
data[:, 2].sum() # 다더하기
user_ids = np.unique(data[:,0]) # 중복제외한 값 다넣기 np.unique
user_ids.shape[0] # 유저수 구하기

result = [] # python의 list
 
    
data[:,0] == 1.0 # 1과 같으면 true

result = []
for user_id in user_ids:
    data_for_user = data[data[:,0] == user_id, :]
    mean_rating_for_user = data_for_user[:,2].mean()
    result.append([user_id, mean_rating_for_user])
result
        
        

[[1.0, 4.366379310344827],
 [2.0, 3.9482758620689653],
 [3.0, 2.4358974358974357],
 [4.0, 3.5555555555555554],
 [5.0, 3.6363636363636362],
 [6.0, 3.4936305732484074],
 [7.0, 3.2302631578947367],
 [8.0, 3.574468085106383],
 [9.0, 3.260869565217391],
 [10.0, 3.2785714285714285],
 [11.0, 3.78125],
 [12.0, 4.390625],
 [13.0, 3.6451612903225805],
 [14.0, 3.3958333333333335],
 [15.0, 3.448148148148148],
 [16.0, 3.7244897959183674],
 [17.0, 4.20952380952381],
 [18.0, 3.7320717131474104],
 [19.0, 2.607396870554765],
 [20.0, 3.590909090909091],
 [21.0, 3.260722347629797],
 [22.0, 2.5714285714285716],
 [23.0, 3.6487603305785123],
 [24.0, 3.65],
 [25.0, 4.8076923076923075],
 [26.0, 3.238095238095238],
 [27.0, 3.5481481481481483],
 [28.0, 3.020175438596491],
 [29.0, 4.1419753086419755],
 [30.0, 4.735294117647059],
 [31.0, 3.92],
 [32.0, 3.7549019607843137],
 [33.0, 3.7884615384615383],
 [34.0, 3.4186046511627906],
 [35.0, 4.086956521739131],
 [36.0, 2.6333333333333333],
 [37.0, 4.142857142857143],